name: Build and Publish

on:
  # run it on push to the default repository branch
 #push:
   # branches: [master]
     
  # run it during pull request
  pull_request:
    types:
      - opened
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'releases/'"
    
      - name: Checkout code
        uses: actions/checkout@v1
        
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build docker images
        run:  docker build  . -t goglang:1.10.0 -f ./guestbook-go/Dockerfile
      - name: tag docker image 
        run: docker tag goglang:1.10.0 dikshasahu/golang-image-new:latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image 
        run: docker  push  dikshasahu/golang-image-new:latest
