name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [master]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
           context: . 
           file: /guestbook-go/Dockerfile  
           push : true
           image: dikshasahu/golang-image-new 
           tags: latest 
     
           
      

  
        
